### ISSUE TITLE
New repo for ML/DL or not?

### ISSUE THREAD

**Issue by mananpal1997** [o-d-i-n/DevBible#25]
If not, discuss about adding it to DevBible separately, because it's a vast field in it's own.

**Comment by mananpal1997** [comment]
CC: @gabru-md @mbad0la

**Comment by gabru-md** [comment]
ML / DL is a vast field of computer science and if we add the matter related to it into the devbible then it would make it not just complicated but also vast.
DevBible is made as an introductory thesis for people new to open source technologies , to let them learn about new languages and frameworks. Whereas ML /DL requires a huge ton of introduction. So incorporating it within devbible is a bad idea, since it is not a "beginner's first choice". 
Therefore i say that it is better to have a new repository for this very purpose.

**Comment by mananpal1997** [comment]
I'm thinking the same thing. Will make a new repo 👍

**Comment by mbad0la** [comment]
@mananpal1997 probably make some notebook styled ML repos. Would be really interactive IMO.
